(()=>{
const $=s=>document.querySelector(s),content=$('#content'),parking=$('.legacy-app-window .main-content'),legacyOpenPage=window.manager777?.openPage?.bind(window.manager777)||(()=>{});let page='home',activeLegacy=null,doctorId='',shareId='',sharePath='',snapshot={loading:true},refreshRevision=0;
const icons={user:'<circle cx="128" cy="88" r="40"/><path d="M48 216a80 80 0 01160 0"/>',link:'<path d="M96 160l64-64M104 80l24-24a51 51 0 0172 72l-24 24M152 176l-24 24a51 51 0 01-72-72l24-24"/>',check:'<path d="M48 132l52 52L208 72"/>',download:'<path d="M128 32v136M72 112l56 56 56-56M40 176v40h176v-40"/>',box:'<rect x="40" y="72" width="176" height="136" rx="16"/><path d="M88 72V48h80v24M40 128h176M104 128v24h48v-24"/>',key:'<circle cx="160" cy="88" r="48"/><path d="M125 123l-85 85H24v-40l72-72M56 152l32 32"/>',settings:'<path d="M40 64h176M40 128h176M40 192h176M88 40v48M168 104v48M104 168v48"/>',chat:'<path d="M40 48h176v136H96l-56 40Z"/><path d="M80 96h96M80 136h64"/>',file:'<path d="M56 24h96l48 48v160H56ZM152 24v48h48M88 120h80M88 160h80"/>',warning:'<path d="M128 32L232 216H24ZM128 96v56M128 184v1"/>',arrow:'<path d="M48 128h160M152 72l56 56-56 56"/>'};
const icon=n=>`<svg viewBox="0 0 256 256" aria-hidden="true">${icons[n]||icons.box}</svg>`,escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message||p.code||`HTTP ${r.status}`);return p;}
const row=(a,b)=>`<div class="summary-row"><span>${a}</span><strong>${b}</strong></div>`,button=(text,action,kind='primary')=>`<button class="${kind}" data-shell-action="${action}">${text}</button>`;
const tools=[['codex','客户端管理','安装、更新、卸载 Codex 客户端','download','客户端'],['home','使用中文界面','构建、启动和恢复中文版','chat','客户端'],['providers','连接密钥','同步、添加和管理 Key','key','连接与模型'],['providers','模型与思考程度','选择模型，检查密钥是否支持','settings','连接与模型'],['extensions','插件与工具','插件、MCP 工具、技能','box','扩展与修复'],['enhance','Codex++ 增强','安装、设置和恢复增强功能','settings','扩展与修复'],['enhance','插件修复','检查插件入口，查看修复过程','box','扩展与修复'],['tool-doctor','工具调用修复','能聊天但不执行工具？用 Tool Doctor 检查','settings','扩展与修复'],['share-package','分享安装包','生成不包含账号、Key 和聊天记录的安全分享包','file','扩展与修复'],['sessions','聊天记录与备份','查找聊天记录、备份与手动恢复','chat','备份与设置'],['sessions','配置备份','查看配置快照与恢复入口','file','备份与设置'],['logs','操作记录','查看进度、错误原因和脱敏日志','file','备份与设置'],['settings','管理工具设置','检查管理工具更新与启动选项','settings','备份与设置']];
function releaseLegacy(){if(activeLegacy&&parking){activeLegacy.classList.remove('shell-tool-active');parking.append(activeLegacy);}activeLegacy=null;}
function nav(){document.querySelectorAll('[data-shell-page]').forEach(b=>{if(b.dataset.shellPage===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
function steps(account,active,installed){const done=[account,active,installed],current=done.findIndex(x=>!x);return `<ol class="progress-steps" aria-label="开始使用的步骤">${['登录账号','连接 GPT','开始使用'].map((x,i)=>`<li class="${done[i]?'done':i===current?'current':''}" ${i===current?'aria-current="step"':''}><span class="step-number">${done[i]?'✓':i+1}</span>${x}</li>`).join('')}</ol>`;}
function hero(symbol,title,description,tone=''){return `<div class="focus-section"><div class="hero-symbol ${tone}">${icon(symbol)}</div><h1>${title}</h1><p>${description}</p></div>`;}
const selectableProvider=x=>x.type==='text'&&!x.platformSync?.disabled&&!x.platformSync?.requiresActivation&&x.adapter?.canActivate!==false;
function providerCard(active,providers){if(!active)return'';const usable=providers.filter(selectableProvider);return `<div class="key-panel"><div class="inline-heading"><label for="shell-key-select">当前连接密钥</label>${button('同步','sync-keys','link')}</div><select id="shell-key-select" aria-label="当前连接密钥">${usable.map(x=>`<option value="${escape(x.id)}" ${x.id===active.id?'selected':''}>${escape(x.name||'未命名连接')}</option>`).join('')}</select><div class="key-meta"><span>${escape(active.groupName||'分组未同步')} · ${Number.isFinite(active.groupMultiplier)?escape(active.groupMultiplier)+'×':'倍率未同步'}</span>${button('管理连接密钥','providers','link')}</div></div>`;}
function toolRows(filter=''){const found=tools.filter(x=>x.slice(1).join(' ').toLowerCase().includes(filter.toLowerCase()));if(!found.length)return '<div class="empty-state">没有找到这个功能，请换一个名称搜索。</div>';return [...new Set(found.map(x=>x[4]))].map(group=>`<section class="tool-section"><h2>${group}</h2><div class="tool-list">${found.filter(x=>x[4]===group).map(x=>`<button class="tool-row" data-legacy-page="${x[0]}"><span class="tool-icon">${icon(x[3])}</span><span class="tool-copy"><strong>${x[1]}</strong><small>${x[2]}</small></span><span class="chevron" aria-hidden="true">›</span></button>`).join('')}</div></section>`).join('');}
function renderTools(){return `<div class="page-head"><h1>工具箱</h1><p>需要调整或修复时，再来这里。</p></div><input class="tool-search" id="shell-tool-search" type="search" aria-label="搜索工具" placeholder="搜索功能，如：汉化、插件修复"><div id="shell-tool-results">${toolRows()}</div>`;}
const known=v=>v===null||v===undefined||v===''?'暂未返回':escape(v);
function renderHome(){const a=snapshot.account||{},providers=(snapshot.providers?.providers||[]).filter(selectableProvider),codex=snapshot.codex||{},logged=a.state==='logged-in',active=providers.find(x=>x.active),installed=!!codex.installed;let h=steps(logged,!!active,installed);if(snapshot.loading)return h+hero('link','正在读取真实状态','不会用示例数据替代账号、密钥或客户端状态。')+'<div class="skeleton"></div><div class="skeleton"></div>';if(snapshot.error)return h+hero('warning','暂时无法读取状态','现有配置没有改动。','error')+`<div class="notice error" role="alert"><strong>加载失败</strong>${escape(snapshot.error)}</div>${button('重新读取','refresh')}`;if(!logged&&!active)return h+hero('user','先登录你的账号','登录 777codes，开始准备你的 GPT。')+`<div class="summary">${row('没有账号？','下一步也可以注册')}${row('登录方式','网页授权 · 不在此输入密码')}</div>${button(`登录 / 注册账号 ${icon('arrow')}`,'login')}<div class="sub-action">${button('已有其他平台密钥？','providers','link')}</div>`;if(!active)return h+hero('link','连接你的 GPT',logged?'同步账号里的连接密钥，再检查是否可用。':'选择一把已经保存的其他平台连接密钥。')+`<div class="empty-state"><strong>还没有可用连接</strong>同步账号 Key，或添加其他平台配置。</div>${button(logged?'同步账号密钥':'添加连接密钥',logged?'sync-keys':'providers')}<div class="sub-action">${button('管理连接密钥','providers','link')}</div>`;const key=providerCard(active,providers),client=row('Codex 客户端',escape(codex.version?`${installed?'已安装':'已检测'} · ${codex.version}`:installed?'已安装':'尚未安装'));if(!installed)return h+hero('download','准备 Codex 客户端','它是你和 GPT 聊天、处理任务的地方。')+`<div class="summary">${row('软件名称','Codex 客户端')}${row('当前模型',escape(active.model||'尚未选择'))}${client}</div>${key}${button('准备 Codex 客户端','codex')}`;return h+hero('check','准备好了，开始吧','以后回来，直接打开就能用。')+`<div class="summary">${row('GPT 连接',active.verifiedAt?'<span class="tag">检查通过</span>':'<span class="tag">已选择 · 未重新检测</span>')}${row('当前模型',escape(active.model||'尚未选择'))}${client}</div>${key}${button(`打开 Codex 客户端，开始聊天 ${icon('arrow')}`,'launch')}<div class="sub-action">${button('想使用中文界面？','home-tool','link')}${button('连接出问题了？','tool-doctor','link')}</div>`;}
function renderAccount(){const a=snapshot.account||{},logged=a.state==='logged-in',offline=a.state==='offline',u=a.user||{},r=snapshot.referral,usage=snapshot.usage;if(snapshot.loading)return '<div class="page-head"><h1>我的账号</h1><p>正在读取真实账号数据。</p></div><div class="skeleton"></div><div class="skeleton"></div>';if(snapshot.error)return `<div class="page-head"><h1>我的账号</h1><p>账号状态无法读取。</p></div><div class="notice error" role="alert"><strong>加载失败</strong>${escape(snapshot.error)}</div>${button('重新读取','refresh')}`;if(!logged)return `<div class="page-head"><h1>我的账号</h1><p>登录后查看余额、同步密钥和分享数据。</p></div><div class="empty-state"><strong>${offline?'平台账号暂时离线':'你还没有登录'}</strong>${offline?'本机登录信息和 Key 没有改动，请稍后刷新。':'使用网页授权登录；管理工具不会要求你在这里输入密码。'}</div>${button(offline?'重新读取':'登录 / 注册账号',offline?'refresh':'login')}`;return `<div class="page-head"><h1>我的账号</h1><p>账号、余额和分享，都在这里。</p></div><section class="account-card"><div class="inline-heading"><strong>${known(u.displayName||u.email||u.id)}</strong><span class="tag">已登录</span></div><p class="subtle" style="margin-top:20px">当前连接密钥余额</p><div class="balance-value">${usage?.remaining===null||usage?.remaining===undefined?'暂未取得':escape(usage.remaining)}</div><div class="inline-heading"><span class="subtle">${snapshot.activeProvider?escape(snapshot.activeProvider.name||'当前 Key'):'未选择连接密钥'}</span>${button('刷新余额','balance-refresh','link')}</div></section><div class="two-buttons">${button('去平台充值','recharge','secondary')}${button('同步账号密钥','sync-keys','secondary')}</div><section class="account-card"><div class="inline-heading"><strong>分享给朋友</strong><span class="subtle">已邀请 ${r?.invitedUserCount??'未取得'} 人</span></div><p class="subtle" style="margin:10px 0">发链接，或生成带有你推广来源的干净安装包。</p><div class="two-buttons">${button('分享安装链接','share-link','secondary')}${button('分享安装包','share-package','secondary')}</div></section>${button('退出登录','logout','link')}`;}
function render(){if(page==='legacy')return;releaseLegacy();nav();const html=page==='home'?renderHome():page==='tools'?renderTools():renderAccount();content.innerHTML=html+(snapshot.accountError?`<div class="shell-status error" role="status">${escape(snapshot.accountError)}</div>`:'');content.scrollTop=0;}
const identity=a=>a?.state==='logged-in'?String(a.user?.id||a.user?.email||''):'';
async function refresh(){const revision=++refreshRevision,requestedPage=page,previous=snapshot;snapshot={...snapshot,loading:!snapshot.account};render();let next;try{const[account,providers,codex]=await Promise.all([api('/api/account/status'),api('/api/providers'),api('/api/codex/status')]);const activeProvider=providers.providers?.find(x=>x.active&&selectableProvider(x)),sameUser=identity(account)&&identity(account)===identity(previous.account),sameKey=sameUser&&activeProvider?.id===previous.activeProvider?.id&&activeProvider?.updatedAt===previous.activeProvider?.updatedAt;next={account,providers,codex,activeProvider,loading:false,...(sameUser?{referral:previous.referral}:{}),...(sameKey?{usage:previous.usage,usageAt:previous.usageAt,accountFetchedAt:previous.accountFetchedAt}:{})};}catch(e){next={...previous,loading:false,...(previous.account?{accountError:`更新失败，显示上次数据：${e.message}`}:{error:e.message})};}if(revision!==refreshRevision)return null;snapshot=next;if(page===requestedPage)render();return revision;}
let accountFlight=null;
const accountView=renderAccount;
renderAccount=()=>{const freshness=`<p class="balance-freshness" role="status">${snapshot.accountRefreshing?'正在后台更新，暂时显示上次数据':snapshot.usageAt?'余额更新于 '+new Date(snapshot.usageAt).toLocaleTimeString():'余额尚未读取'}</p>`;return accountView().replace(/(<div class="balance-value">[^<]*<\/div>)/,'$1'+freshness);};
document.addEventListener('click',event=>{const action=event.target.closest('[data-shell-action]')?.dataset.shellAction;if(action==='balance-refresh'||action==='refresh'&&page==='account'){event.preventDefault();event.stopImmediatePropagation();void refreshAccount(true);}},true);
function refreshAccount(force=false){
 if(accountFlight)return accountFlight;
 if(!force&&snapshot.accountFetchedAt&&Date.now()-snapshot.accountFetchedAt<30000){render();return Promise.resolve();}
 accountFlight=(async()=>{const revision=await refresh();if(revision===null)return;const activeId=snapshot.activeProvider?.id,userId=identity(snapshot.account);if(!userId)return;
 snapshot.accountRefreshing=true;render();
 const [referral,usage]=await Promise.allSettled([api('/api/account/referral'),activeId?api('/api/providers/usage',{id:activeId}):Promise.resolve(null)]);
 if(revision!==refreshRevision||identity(snapshot.account)!==userId)return;
 snapshot.accountRefreshing=false;snapshot.accountFetchedAt=Date.now();const errors=[];
 if(referral.status==='fulfilled')snapshot.referral=referral.value;else errors.push(`邀请数据更新失败：${referral.reason.message}`);
 if(usage.status==='fulfilled'){snapshot.usage=usage.value?.usage;snapshot.usageAt=Date.now();}else errors.push(`余额更新失败，保留上次数据：${usage.reason.message}`);
 snapshot.accountError=errors.join('；');render();
 })().finally(()=>{accountFlight=null;});return accountFlight;
}
async function openLegacy(id){releaseLegacy();legacyOpenPage(id);const section=$(`#page-${id}`);if(!section)return;activeLegacy=section;content.replaceChildren(section);section.classList.add('shell-tool-active');section.querySelector('.legacy-back')?.remove();const back=document.createElement('button');back.className='back legacy-back';back.textContent='‹ 返回工具箱';back.dataset.shellAction='tools';section.prepend(back);page='legacy';nav();content.scrollTop=0;if(id==='tool-doctor')await refreshTargets();if(id==='share-package')await refreshReferral();}
async function refreshTargets(){try{const p=await api('/api/tool-doctor/targets'),s=$('#doctor-binary');$('#doctor-home').value=p.home||'';s.replaceChildren(...((p.targets||[]).length?p.targets.map(x=>new Option(`${x.source||'Codex CLI'} · ${x.version||'版本未知'} · ${x.path}`,x.path)):[new Option('未找到可信 Codex CLI','')]));}catch(e){show('#windows-tool-output',e.message,true);}}
let sharePackages=[],shareBusy=false,shareLoading=false,shareReferralReady=false,shareReleaseRevision=0;
const shareEnvironments=[['manager-windows','Windows'],['manager-macos-arm64','Mac Apple 芯片'],['manager-macos-x64','Mac Intel']];
const sizeLabel=n=>n===null||n===undefined||n===''||!Number.isFinite(Number(n))||Number(n)<0?'大小暂未提供':Number(n)===0?'0 B':Number(n)<1024?`${Number(n)} B`:Number(n)<1048576?`${(Number(n)/1024).toFixed(1)} KB`:`${(Number(n)/1048576).toFixed(1)} MB`;
function shareControls(){const selected=sharePackages.find(p=>p.id===$('#share-package-version')?.value);for(const id of ['share-package-version','share-choose','share-output','share-releases-retry']){const el=$('#'+id);if(el)el.disabled=shareBusy||shareLoading;}const create=$('#share-package-create');if(create){create.disabled=shareBusy||shareLoading||!shareReferralReady||!selected?.available||!$('#share-output')?.value.trim();create.textContent=shareBusy?'正在下载并生成…':'下载并生成分享包';}if($('#share-cancel'))$('#share-cancel').disabled=!shareBusy;}
function shareSelection(){const p=sharePackages.find(p=>p.id===$('#share-package-version')?.value),info=$('#share-release-info');if(info){info.textContent=p?`${p.label}\n${p.available?`版本 ${p.version||'未提供'} · ${sizeLabel(p.sizeBytes)}\n${p.cached===true?'已缓存，生成前仍会校验文件':p.cached===false?'尚未缓存，生成时自动下载':'生成时自动检查本机缓存并校验文件'}`:p.message||'此版本暂时不可用，请选择其他版本或稍后刷新。'}`:'暂无可生成的版本，请稍后刷新。';info.classList.toggle('error',!p?.available);}shareControls();}
async function refreshShareReleases(){const revision=++shareReleaseRevision;shareLoading=true;shareControls();const info=$('#share-release-info');if(info){info.textContent='正在向平台查询版本与下载大小…';info.classList.remove('error');}try{const result=await api('/api/share-package/releases');if(result.ok===false)throw new Error(result.message||'平台暂时无法提供安装版本。');if(revision!==shareReleaseRevision)return;const packages=Array.isArray(result.packages)?result.packages:[];sharePackages=shareEnvironments.map(([id,label])=>({...packages.find(p=>p.id===id),id,label,available:packages.some(p=>p.id===id&&p.available===true)}));const select=$('#share-package-version'),previous=select.value;select.innerHTML=sharePackages.map(p=>`<option value="${p.id}" ${p.available?'':'disabled'}>${p.label}${p.available?'':' · 暂不可用'}</option>`).join('');select.value=sharePackages.find(p=>p.id===previous&&p.available)?.id||sharePackages.find(p=>p.available)?.id||sharePackages[0].id;shareLoading=false;shareSelection();}catch(e){if(revision!==shareReleaseRevision)return;sharePackages=[];shareLoading=false;$('#share-package-version').innerHTML='<option value="">版本读取失败</option>';info.textContent=`无法读取可用版本：${e.message}。请检查网络或登录状态，再点击“刷新可用版本”。`;info.classList.add('error');shareControls();}}
async function refreshReferral(){shareReferralReady=false;shareControls();await Promise.all([refreshShareReleases(),(async()=>{try{const p=await api('/api/account/referral'),s=$('#share-url');s.value=p.shareUrl||'';s.readOnly=true;shareReferralReady=!!s.value;if(!shareReferralReady)throw new Error('分享链接尚未取得，请先登录账号后重试。');}catch(e){show('#share-output-live',`无法读取你的分享链接：${e.message}`,true);}finally{shareControls();}})()]);}
function show(sel,text,bad=false){const e=$(sel);if(e){e.textContent=text;e.classList.toggle('error',bad);}if(bad){snapshot.accountError=String(text);if(page==='legacy'&&content){let alert=content.querySelector('.shell-route-error');if(!alert){alert=document.createElement('div');alert.className='notice error shell-route-error';alert.setAttribute('role','alert');content.prepend(alert);}alert.textContent=String(text);}else render();}}
async function pollDoctor(){if(!doctorId)return;try{const t=(await api(`/api/tool-doctor/status?id=${encodeURIComponent(doctorId)}`)).task;const failed=t.state==='failed';show('#windows-tool-output',failed?`检查未完成\n${t.error?.message||'请查看检查报告。'}`:`${taskPhaseLabel('doctor',t.phase)}${t.state==='running'?` · 进度 ${t.progress}%（不是通过率）`:''}${t.message?`\n${t.message}`:''}`,failed);$('#doctor-progress').value=t.progress||0;$('#doctor-cancel').disabled=t.state!=='running';$('#doctor-report').disabled=!t.reportPath;if(t.state==='running')setTimeout(()=>void pollDoctor(),700);}catch(e){show('#windows-tool-output',`状态暂时未知：${e.message}。可重新进入此页重试。`,true);}}
async function pollShare(){if(!shareId)return;try{const t=(await api(`/api/share-package/status?id=${encodeURIComponent(shareId)}`)).task;if(!t)throw new Error('服务未返回生成任务');const phase=taskPhaseLabel('share',t.phase);shareBusy=t.state==='running'||t.state==='queued';show('#share-output-live',`${phase} · ${Math.round(Number(t.progress)||0)}%${t.message?`\n${t.message}`:''}${t.totalBytes?`\n已下载 ${sizeLabel(t.downloadedBytes)} / ${sizeLabel(t.totalBytes)}`:''}${t.error?`\n${t.error.message||t.error}`:''}${t.path&&!shareBusy&&t.state!=='failed'&&t.state!=='cancelled'?`\n${t.path}\n${sizeLabel(t.bytes)}\nSHA-256 ${t.sha256||'未返回'}`:''}`,t.state==='failed');$('#share-progress').value=t.progress||0;if(t.path&&!shareBusy&&t.state!=='failed'&&t.state!=='cancelled'){sharePath=t.path;$('#share-open').disabled=false;$('#share-copy').disabled=false;}shareControls();if(shareBusy)setTimeout(()=>void pollShare(),700);}catch(e){show('#share-output-live',`状态暂时未知：${e.message}。正在重新查询，请勿重复生成。`,true);if(shareBusy)setTimeout(()=>void pollShare(),2500);}}
function taskPhaseLabel(kind,phase){const common={queued:'等待开始',running:'正在处理',completed:'处理完成',cancelled:'已取消',failed:'处理失败'},specific=kind==='share'?{downloading:'正在下载',download:'正在下载',validating:'正在校验安装包',verifying:'正在校验安装包',hashing:'正在校验文件完整性',scanning:'正在检查安装包内容',compressing:'正在压缩分享包',packaging:'正在生成分享包',ready:'分享包已准备好',cached:'已找到本机缓存',completed:'生成完成',done:'生成完成',failed:'生成失败'}:{'saving-report':'正在保存检查报告',completed:'检查处理完成',failed:'检查处理失败'};return specific[phase]||common[phase]||'正在处理';}
const requestApi=api;
api=async(path,body)=>{const result=await requestApi(path,body);if(path==='/api/providers/switch'){await window.manager777?.refreshProviders?.();const legacyKey=$('#home-key-select');if(legacyKey){legacyKey.value=body.id;legacyKey.dispatchEvent?.(new Event('change',{bubbles:true}));}await window.manager777?.refreshProviders?.();}return result;};
function proxy(id){document.querySelector(id)?.click();}
async function syncKeys(){if(snapshot.account?.state!=='logged-in')throw new Error(snapshot.account?.state==='offline'?'平台账号暂时离线，未修改本地 Key。':'请先登录 777codes，再同步账号密钥。');const result=await api('/api/account/keys/sync',{});await window.manager777?.refreshProviders?.();await refresh();snapshot.accountError=`同步完成：共 ${result.total} 个有效 Key，新增 ${result.added}，更新 ${result.updated}，禁用 ${result.disabled}。当前 Key 未自动切换。`;render();}
document.addEventListener('input',e=>{if(e.target.id==='shell-tool-search')$('#shell-tool-results').innerHTML=toolRows(e.target.value);});
document.addEventListener('input',e=>{if(e.target.id==='share-output')shareControls();});
document.addEventListener('change',e=>{if(e.target.id==='share-package-version')shareSelection();});
document.addEventListener('click',async e=>{
const id=e.target.closest('button')?.id;if(!['share-releases-retry','share-choose','share-package-create','share-cancel','share-open','share-copy'].includes(id))return;
e.preventDefault();e.stopImmediatePropagation();
try{
if(id==='share-releases-retry'){if(!shareBusy)await refreshReferral();return;}
if(id==='share-choose'){if(shareBusy)return;const p=await api('/api/share-package/choose-output',{});if(p.path)$('#share-output').value=p.path;shareControls();return;}
if(id==='share-package-create'){
if(shareBusy)return;const selected=sharePackages.find(p=>p.id===$('#share-package-version').value),outputDirectory=$('#share-output').value.trim();
if(!selected?.available)throw new Error('请选择当前可用的电脑版本。');if(!shareReferralReady)throw new Error('请先登录账号并读取分享链接。');if(!outputDirectory)throw new Error('请先选择保存位置。');
shareBusy=true;sharePath='';$('#share-open').disabled=true;$('#share-copy').disabled=true;$('#share-progress').value=0;shareControls();show('#share-output-live','正在创建任务，随后自动下载并校验安装包…');
try{const p=await api('/api/share-package/start',{packageId:selected.id,outputDirectory});if(!p.task?.id)throw new Error(p.message||'服务未返回生成任务，请刷新后检查。');shareId=p.task.id;void pollShare();}catch(error){shareBusy=false;shareControls();throw error;}return;
}
if(id==='share-cancel'&&shareId&&shareBusy){const p=await api('/api/share-package/cancel',{id:shareId});show('#share-output-live',p.message||'已请求取消，正在等待当前安全步骤结束。');return;}
if(id==='share-open'&&shareId&&sharePath)await api('/api/share-package/open-output',{id:shareId});
if(id==='share-copy'&&sharePath){await navigator.clipboard.writeText(sharePath);show('#share-output-live',`已复制路径\n${sharePath}`);}
}catch(error){show('#share-output-live',error.message,true);}
},true);
document.addEventListener('click',async e=>{if(e.target.closest('[data-shell-action="recharge"]')){e.preventDefault();e.stopImmediatePropagation();try{await api('/api/account/open-platform',{});snapshot.accountError='已打开 777codes 平台，请在网页内查看余额或充值；管理工具不会代为扣款。';}catch(error){snapshot.accountError=`暂时无法打开平台：${error.message}`;}render();}},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-legacy-page="home"],[data-shell-action="home-tool"]')){e.preventDefault();e.stopImmediatePropagation();proxy('#home-codex-zh');}},true);
document.addEventListener('click',e=>{const row=e.target.closest('[data-legacy-page="sessions"]');if(row?.textContent.includes('配置备份')){e.preventDefault();e.stopImmediatePropagation();proxy('#codex-snapshots');}},true);
document.addEventListener('change',async e=>{if(e.target.id!=='shell-key-select')return;const next=snapshot.providers?.providers?.find(x=>x.id===e.target.value),before=snapshot.activeProvider;if(!next||next.id===before?.id)return;if(!await window.manager777.confirm(`切换到 ${next.name||'所选 Key'} 并用于新会话？同步列表不会自动切换；取消不会修改配置。`)){e.target.value=before?.id||'';return;}try{await api('/api/providers/switch',{id:next.id,name:next.name,model:next.model,reasoningEffort:next.reasoningEffort,expectedUpdatedAt:next.updatedAt,confirm:'SWITCH_PROVIDER'});await refresh();}catch(error){e.target.value=before?.id||'';snapshot.accountError=`切换失败：${error.message}`;render();}});
document.addEventListener('click',async e=>{const shellPage=e.target.closest('[data-shell-page]')?.dataset.shellPage,legacy=e.target.closest('[data-legacy-page]')?.dataset.legacyPage,action=e.target.closest('[data-shell-action]')?.dataset.shellAction;try{if(shellPage){page=shellPage;render();if(page==='account')void refreshAccount();return;}if(legacy){if(legacy==='home'){await openLegacy('home');document.querySelector('#page-home #tool-codex-zh')?.scrollIntoView();}else await openLegacy(legacy);return;}if(action){if(['home','tools','account'].includes(action)){page=action;render();if(page==='account')void refreshAccount();return;}if(action==='refresh'){void (page==='account'?refreshAccount():refresh());return;}if(action==='login'){proxy('#account-entry');return;}if(action==='providers'){await openLegacy('providers');return;}if(action==='codex'){await openLegacy('codex');return;}if(action==='launch'){proxy('#home-start-with-key');return;}if(action==='home-tool'){await openLegacy('home');return;}if(action==='tool-doctor'){await openLegacy('tool-doctor');return;}if(action==='sync-keys'){await syncKeys();return;}if(action==='balance-refresh'){await refreshAccount();return;}if(action==='share-link'){const url=snapshot.referral?.shareUrl;if(!url)throw new Error('分享链接暂未取得，请刷新后重试。');await navigator.clipboard.writeText(url);snapshot.accountError='分享链接已复制。';render();return;}if(action==='share-package'){await openLegacy('share-package');return;}if(action==='logout'){if(!await window.manager777.confirm('退出 777codes 平台账号？只清除此客户端的设备登录，不删除 Key 配置。'))return;await api('/api/account/logout',{});await refresh();return;}}
if(e.target.id==='shell-expand')await window.window777?.toggleSize();if(e.target.id==='shell-minimize')await window.window777?.minimize();if(e.target.id==='shell-close')await window.window777?.close();if(e.target.id==='shell-version')await openLegacy('settings');
const d=e.target.closest('[data-doctor-command]');if(d){const command=d.dataset.doctorCommand,paid=['diagnose','verify','plan','apply','repair'].includes(command),write=['apply','repair','rollback','recover'].includes(command);if(paid&&!confirm('检测或验证可能消耗 API 额度，是否继续？'))return;if(write&&!confirm('事务步骤不会被强制中断。确认继续？'))return;const p=await api('/api/tool-doctor/start',{command,home:$('#doctor-home').value.trim(),binary:$('#doctor-binary').value.trim(),consent:paid?'ALLOW_PAID_TOOL_TEST':undefined,confirm:write?`DOCTOR_${command.toUpperCase()}`:undefined});doctorId=p.task.id;void pollDoctor();}
if(e.target.id==='doctor-cancel'&&doctorId){const p=await api('/api/tool-doctor/cancel',{id:doctorId});show('#windows-tool-output',p.message);}if(e.target.id==='doctor-report'&&doctorId){const report=await api(`/api/tool-doctor/report?id=${encodeURIComponent(doctorId)}`),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download=`tool-doctor-${doctorId}.json`;a.click();URL.revokeObjectURL(a.href);}
}catch(err){show(activeLegacy?.id==='page-share-package'?'#share-output-live':'#windows-tool-output',err.message,true);}});
document.querySelectorAll('.legacy-app-window dialog').forEach(dialog=>document.body.append(dialog));
document.querySelectorAll('.legacy-app-window .modal-backdrop').forEach(modal=>document.body.append(modal));
// The original navigator is captured above and does not call this wrapper.
// Network loading must never lock navigation to another tool page.
if(window.manager777)window.manager777.openPage=id=>{if(['home','tools','account'].includes(id)){page=id;render();if(id==='account')void refreshAccount();return;}return openLegacy(id);};
const accountDialog=$('#account-dialog'),accountName=$('#account-name');
accountDialog?.addEventListener?.('close',()=>void refresh());
if(accountName&&typeof MutationObserver!=='undefined')new MutationObserver(()=>void refresh()).observe(accountName,{childList:true,characterData:true,subtree:true});
window.demoAlignedUI=Object.freeze({refresh,refreshAccount,getSnapshot:()=>structuredClone(snapshot),selectors:Object.freeze({app:'#onboarding-app',content:'#content',home:'[data-shell-page="home"]',tools:'[data-shell-page="tools"]',account:'[data-shell-page="account"]',key:'#shell-key-select',accountCard:'.account-card',balance:'.balance-value'})});
window.addEventListener('manager777:account-changed',()=>void refresh());void refresh();
})();
