import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash,randomBytes } from 'node:crypto';
import { mkdtemp,mkdir,readFile,readdir,rm,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { inflateRawSync } from 'node:zlib';
import { SharePackageManager,zipEntryNames } from '../js/share-package-manager.mjs';

let crcTable;function crc32(b){crcTable||=Array.from({length:256},(_,n)=>{let c=n;for(let i=0;i<8;i++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});let c=0xffffffff;for(const x of b)c=crcTable[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function zip(rows){const local=[],central=[];let offset=0;for(const [name,value,attrs=0]of rows){const n=Buffer.from(name),d=Buffer.from(value),crc=crc32(d),h=Buffer.alloc(30),c=Buffer.alloc(46);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt32LE(crc,14);h.writeUInt32LE(d.length,18);h.writeUInt32LE(d.length,22);h.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(attrs?0x314:20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt32LE(crc,16);c.writeUInt32LE(d.length,20);c.writeUInt32LE(d.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(attrs>>>0,38);c.writeUInt32LE(offset,42);local.push(h,n,d);central.push(c,n);offset+=h.length+n.length+d.length;}const end=Buffer.alloc(22),centralSize=central.reduce((n,b)=>n+b.length,0);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(rows.length,8);end.writeUInt16LE(rows.length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,...central,end]);}
function entry(buffer,wanted){let p=buffer.indexOf(Buffer.from('PK\x01\x02','binary'));while(p>=0){const flags=buffer.readUInt16LE(p+8),method=buffer.readUInt16LE(p+10),cs=buffer.readUInt32LE(p+20),nl=buffer.readUInt16LE(p+28),xl=buffer.readUInt16LE(p+30),cl=buffer.readUInt16LE(p+32),off=buffer.readUInt32LE(p+42),name=buffer.subarray(p+46,p+46+nl).toString(flags&0x800?'utf8':'latin1');if(name===wanted){const start=off+30+buffer.readUInt16LE(off+26)+buffer.readUInt16LE(off+28),raw=buffer.subarray(start,start+cs);return method===0?raw:inflateRawSync(raw);}p=buffer.indexOf(Buffer.from('PK\x01\x02','binary'),p+46+nl+xl+cl);}throw new Error(`missing ${wanted}`);}
const shareUrl='https://www.777codes.codes/download/777codex?ref=safe_ref';
for(const arch of ['arm64','x64'])test(`Mac ${arch} wrapper preserves original ZIP including executable modes and symlinks`,async t=>{
 const f=await fixture([['777 Codex.app/Contents/MacOS/main',Buffer.from('mach-o-fixture'),0x81ed0000],['777 Codex.app/Versions/Current',Buffer.from('A'),0xa0000000]]);t.after(()=>rm(f.root,{recursive:true,force:true}));
 const release={...f.trusted,platform:'mac',arch};let acquired=false;
 const manager=new SharePackageManager({trustedRelease:async()=>f.trusted,releaseSource:{release:async()=>release,acquire:async()=>{acquired=true;return f.base;}}});
 const r=await manager.create({packageId:'manager-macos-'+arch,outputDirectory:f.out});assert.ok(acquired);const b=await readFile(r.path),name=arch==='arm64'?'Mac-Apple-公测版-1.0.zip':'Mac-Intel-公测版-1.0.zip';assert.deepEqual(entry(b,name),f.bytes);assert.ok(zipEntryNames(b).includes('先注册账号.webloc'));assert.equal(JSON.parse(entry(b,'referral.json')).arch,arch);
});
async function fixture(rows){const root=await mkdtemp(join(tmpdir(),'share-safe-')),base=join(root,'base.zip'),out=join(root,'输出目录'),bytes=zip(rows);await writeFile(base,bytes);await mkdir(out);const trusted={sha256:createHash('sha256').update(bytes).digest('hex'),sizeBytes:bytes.length,shareUrl};return{root,base,out,bytes,trusted,manager:new SharePackageManager({trustedRelease:async()=>trusted})};}

test('uses only the trusted release URL, preserves exe bytes, UTF-8 names and compression',async t=>{const exe=Buffer.alloc(3*1024*1024,0x41),f=await fixture([['中文目录/',Buffer.alloc(0)],['中文目录/777Codex.exe',exe],['中文目录/readme.txt',Buffer.from('ok')]]);t.after(()=>rm(f.root,{recursive:true,force:true}));await assert.rejects(f.manager.create({basePackage:f.base,outputDirectory:f.out,shareUrl:'https://www.777codes.codes/download/777codex?ref=attacker'}),e=>e.code==='SHARE_REF_MISMATCH');const result=await f.manager.create({basePackage:f.base,outputDirectory:f.out});const made=await readFile(result.path),names=zipEntryNames(made);assert.ok(names.includes('中文目录/先注册账号.url'));assert.deepEqual(entry(made,'中文目录/777Codex.exe'),exe);assert.match(entry(made,'中文目录/referral.json').toString(),/"signed":false/);assert.ok(result.bytes<exe.length/4,'compressible input must not be emitted as STORE');});
test('checks size and digest before attempting to parse or expand ZIP',async t=>{const root=await mkdtemp(join(tmpdir(),'share-order-')),base=join(root,'broken.zip');t.after(()=>rm(root,{recursive:true,force:true}));await writeFile(base,Buffer.alloc(22,1));const manager=new SharePackageManager({trustedRelease:async()=>({sha256:'0'.repeat(64),sizeBytes:22,shareUrl})});await assert.rejects(manager.create({basePackage:base,outputDirectory:root}),e=>e.code==='SHARE_BASE_HASH_MISMATCH');});
for(const [label,name,attrs]of [['sensitive','release/auth.json',0],['traversal','release/../evil',0],['ADS','release/file.txt:secret',0],['case duplicate','RELEASE/777CODEX.EXE',0],['symlink','release/link',0xA0000000]])test(`rejects ${label} entries`,async t=>{const rows=[['release/777Codex.exe',Buffer.from('exe')],[name,Buffer.from('x'),attrs]],f=await fixture(rows);t.after(()=>rm(f.root,{recursive:true,force:true}));await assert.rejects(f.manager.create({basePackage:f.base,outputDirectory:f.out}),e=>e.code==='SHARE_ZIP_UNSAFE');});
test('EOCD parser rejects appended fake central-directory magic',()=>{const good=zip([['777Codex.exe',Buffer.from('x')]]);assert.throws(()=>zipEntryNames(Buffer.concat([good,Buffer.from('PK\x01\x02junk','binary')])),e=>e.code==='SHARE_ZIP_INVALID');});
test('real worker cancellation waits for handles and removes every unpublished artifact',async t=>{const f=await fixture([['release/777Codex.exe',randomBytes(16*1024*1024)],['release/readme.txt',Buffer.from('ok')]]);t.after(()=>rm(f.root,{recursive:true,force:true}));let cancel=false;await assert.rejects(f.manager.create({basePackage:f.base,outputDirectory:f.out},phase=>{if(phase==='compressing')cancel=true;},()=>cancel),e=>e.code==='TASK_CANCELLED');assert.deepEqual(await readdir(f.out),[]);assert.ok(!(await readdir(f.root)).some(n=>/\.partial(?:\.json)?$/.test(n)));});
for(const name of ['release/CON.txt','release/trailing.','release/trailing ','release//empty'])test(`rejects Windows-ambiguous path ${name}`,async t=>{const f=await fixture([['release/777Codex.exe',Buffer.from('exe')],[name,Buffer.from('x')]]);t.after(()=>rm(f.root,{recursive:true,force:true}));await assert.rejects(f.manager.create({basePackage:f.base,outputDirectory:f.out}),e=>e.code==='SHARE_ZIP_UNSAFE');});
