import packager from 'electron-packager';
import {mkdtemp,mkdir,cp,readFile,writeFile,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
const exec=promisify(execFile);
if(process.platform!=='darwin')throw new Error('Build and signature verification require macOS');
const arch=process.argv[2]||process.arch;
if(!['arm64','x64'].includes(arch)||arch!==process.arch)throw new Error('Use a native runner for each architecture');
const root=resolve('.');const temp=await mkdtemp(join(tmpdir(),'777codex-package-'));const stage=join(temp,'source');await mkdir(stage);
for(const name of ['index.html','styles.css','ui.js','features-ui.js','account-ui.js','install-ui.js','import-ui.js','mac-ui.js','js','electron'])await cp(join(root,name),join(stage,name),{recursive:true});
await mkdir(join(stage,'scripts'));for(const name of ['server.mjs','feature-api.mjs'])await cp(join(root,'scripts',name),join(stage,'scripts',name));
await mkdir(join(stage,'assets'));await cp(join(root,'assets','777codes-logo.png'),join(stage,'assets','777codes-logo.png'));
const manifest=JSON.parse(await readFile(join(root,'package.json'),'utf8'));const dependencies=manifest.dependencies;
await writeFile(join(stage,'package.json'),JSON.stringify({name:manifest.name,version:manifest.version,private:true,type:'module',main:'electron/main-mac.mjs',dependencies},null,2));
await mkdir(join(stage,'node_modules'),{recursive:true});
for(const name of ['@iarna/toml','yaml'])await cp(join(root,'node_modules',name),join(stage,'node_modules',name),{recursive:true});
let html=await readFile(join(stage,'index.html'),'utf8');
html=html.replace('<script src="./ui.js">','<script src="./mac-ui.js"></script>\n  <script src="./ui.js">').replaceAll('r43 便携试验版','macOS r44 测试版').replaceAll('r43 便携版','macOS r44').replace('解压后运行，需保留完整程序目录；用户配置仍保存在当前 Windows 用户目录。此试验包尚未签名。','解压后将 777Codex.app 放入 Applications。配置保存在当前用户目录。无 Developer ID 签名或 Apple 公证。');
await writeFile(join(stage,'index.html'),html);
let accountUi=await readFile(join(stage,'account-ui.js'),'utf8');await writeFile(join(stage,'account-ui.js'),accountUi.replaceAll('Windows 安全存储','macOS 钥匙串安全存储'));
await writeFile(join(stage,'js','build-info.mjs'),`export const BUILD_INFO=Object.freeze({product:'777codex-desktop',version:'0.11.0',revision:44,revisionLabel:'mac-r44',channel:'mac-test',updateManifestUrl:''});\n`);
const icons=join(temp,'777codes.iconset');await mkdir(icons);
for(const size of [16,32,128,256,512])for(const scale of [1,2])await exec('/usr/bin/sips',['-z',String(size*scale),String(size*scale),join(root,'assets','777codes-logo.png'),'--out',join(icons,`icon_${size}x${size}${scale===2?'@2x':''}.png`)]);
const icns=join(temp,'777codes.icns');await exec('/usr/bin/iconutil',['-c','icns',icons,'-o',icns]);
const electronVersion=JSON.parse(await readFile(join(root,'node_modules','electron','package.json'),'utf8')).version;
const [output]=await packager({dir:stage,name:'777Codex',platform:'darwin',arch,electronVersion,out:join(temp,'packed'),asar:true,prune:false,icon:icns,appBundleId:'codes.777.manager',appVersion:'0.11.0',buildVersion:'44',protocols:[{name:'777codes Import',schemes:['codes777']}],osxSign:false,extendInfo:{LSMinimumSystemVersion:'12.0',NSAppleEventsUsageDescription:'仅在你点击重启时请求退出 Codex。'}});
const appPath=join(output,'777Codex.app');
await exec('/usr/bin/codesign',['--force','--deep','--sign','-',appPath],{maxBuffer:4*1024*1024});
await exec('/usr/bin/codesign',['--verify','--deep','--strict','--verbose=2',appPath]);
const executable=join(appPath,'Contents','MacOS','777Codex');
const binaryArch=(await exec('/usr/bin/lipo',['-archs',executable])).stdout.trim();
if(binaryArch!==(arch==='x64'?'x86_64':'arm64'))throw new Error('Wrong Mach-O architecture: '+binaryArch);
const dist=join(root,'dist-mac');await mkdir(dist,{recursive:true});const smokeRoot=await realpath(await mkdtemp(join(tmpdir(),'777codex-smoke-')));const report=join(dist,`mac-${arch}-smoke.json`);
await exec(executable,[],{timeout:60000,maxBuffer:4*1024*1024,env:{...process.env,MANAGER777_ISOLATED:'1',MANAGER777_ROOT:join(smokeRoot,'manager'),MANAGER777_CODEX_ROOT:join(smokeRoot,'codex'),MANAGER777_SKILL_ROOT:join(smokeRoot,'skills'),MANAGER777_MAC_SMOKE:report,PORT:'0'}});
const smoke=JSON.parse(await readFile(report,'utf8'));if(!smoke.ok||smoke.arch!==arch)throw new Error('Packaged smoke failed');
const zip=join(dist,`777Codex-0.11.0-mac-r44-${arch}-test.zip`);
await exec('/usr/bin/ditto',['-c','-k','--sequesterRsrc','--keepParent',appPath,zip],{timeout:120000});
const sha=createHash('sha256').update(await readFile(zip)).digest('hex');
await writeFile(join(dist,`SHA256-${arch}.txt`),`${sha}  ${zip.split('/').at(-1)}\n`);
await writeFile(join(dist,`mac-${arch}-build.json`),JSON.stringify({version:'0.11.0',revision:'mac-r44',arch,binaryArch,electronVersion,signature:'ad-hoc only; no Developer ID',notarized:false,ciSmoke:smoke,realUserMacAcceptance:false,sha256:sha,commit:process.env.GITHUB_SHA||null},null,2));
console.log('Built, ad-hoc signature verified, and packaged UI smoke passed: '+zip);
